'use strict';

module.exports = {
  COMMAND_LIST: 'list',
  COMMAND_HOST: 'host',
  COMMAND_HELP: 'help',
  ZONE_LIST: [
      'asia-east1-a',
      'asia-east1-b',
      'asia-east1-c',
      'asia-northeast1-a',
      'asia-northeast1-b',
      'asia-northeast1-c',
      'asia-southeast1-a',
      'asia-southeast1-b',
      'australia-southeast1-a',
      'australia-southeast1-b',
      'australia-southeast1-c',
      'europe-west1-b',
      'europe-west1-c',
      'europe-west2-a',
      'europe-west2-b',
      'europe-west2-c',
      'europe-west3-a',
      'europe-west3-b',
      'europe-west3-c',
      'southamerica-east1-a',
      'southamerica-east1-b',
      'southamerica-east1-c',
      'us-central1-a',
      'us-central1-b',
      'us-central1-c',
      'us-central1-f',
      'us-east1-b',
      'us-east1-c',
      'us-east1-d',
      'us-east4-a',
      'us-east4-b',
      'us-east4-c',
      'us-west1-a',
      'us-west1-b',
      'us-west1-c',
      'asia-northeast1-a',
      'asia-northeast1-b',
      'asia-northeast1-c',
      'asia-southeast1-a',
      'asia-southeast1-b',
      'australia-southeast1-a',
      'australia-southeast1-b',
      'australia-southeast1-c',
      'europe-west1-b',
      'europe-west1-c',
      'europe-west1-d',
      'europe-west2-a',
      'europe-west2-b',
      'europe-west2-c',
      'europe-west3-a',
      'europe-west3-b',
      'europe-west3-c',
      'southamerica-east1-a',
      'southamerica-east1-b',
      'southamerica-east1-c',
      'us-central1-a',
      'us-central1-b',
      'us-central1-c',
      'us-central1-f',
      'us-east1-b',
      'us-east1-c',
      'us-east1-d',
      'us-east4-a',
      'us-east4-b',
      'us-east4-c',
      'us-west1-a',
      'us-west1-b',
      'us-west1-c'
  ],
  DEFAULT_HOST_IP: '/externalIP',
  GCE_OPTIONS_FILENAME: '.gce-options',
  HOSTVAR_CACHE_FILENAME: '.gce-hostvar-cache'
};
